function(list_remove_contain list_name contain_text)
    set(modified_list ${${list_name}})
    foreach(item ${modified_list})
        string(REPLACE ${CMAKE_SOURCE_DIR}/src "" shourt_item ${item})
        if (${shourt_item} MATCHES ${contain_text})
            list(REMOVE_ITEM modified_list ${item})
        endif()
    endforeach()
    set(${list_name} ${modified_list} PARENT_SCOPE)
endfunction()
